# Define docker compose version we want to use
version: "3.9"
# Define needed services
services:

    db:
        image: postgres
        # Restarts the db if it encounters an error
        restart: unless-stopped
        # Defines the user, password and database to default to.
        # These should be the same as the values in the ormconfig
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        # Defines what folders to save. here we save the posgres data
        volumes: 
            - data:/var/lib/postgresql/data
        # Allows a bridge between the containers to be made
        ports: 
            - 5432:5432


    kfcboy:
        # Tell's docker to wait till db starts successfully
        depends_on: 
            - db
        restart: unless-stopped
        build: .
        volumes: 
            - kfcboy:/usr/src/app/settings.sqlite3"



# Define what volume to be Shared/saved. will create them if not found
volumes: 
    data: 
    kfcboy:

networks: 
    default:
        driver:  bridge


